const ActionType = {
    ADDQUIZ : "ADDQUIZ",
    TOGGLEACTIVE:"TOGGLEACTIVE",
    DELETEQUIZ:"DELETEQUIZ",
    PLAYQUIZ:"PLAYQUIZ",
    GETNAME : "GETNAME",
    GETANSWER:"GETANSWER",
    RESET:"RESET"
};

export default ActionType;